spring:
 mvc:
  view:
   prefix: /jsp/
   suffix: .jsp
 datasource:
  url: jdbc:mysql://localhost:3306/TravelCompany?useSSL=false
  username: root
  password: 1111
  testWhileIdle: true
  validationQuery: SELECT 1
 jpa:
  show-sql: true
  hibernate: 
   ddl-auto: update
   naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
  properties: 
   hibernate:
    dialect: org.hibernate.dialect.MySQL5Dialect
 